# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(max_length=200)),
                ('contacts', models.ManyToManyField(to='api.Contact')),
            ],
        ),
    ]
