# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='note',
            field=models.TextField(max_length=500),
        ),
    ]
