# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171007_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[(1, 'Career'), (2, 'Social'), (3, 'Family'), (4, 'Dating'), (5, 'Obligation'), (6, 'Worthwhile'), (7, 'Time Waste')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='tags',
            field=models.ManyToManyField(to='api.InteractionTag'),
        ),
    ]
